[package]
name = "insidious"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
walkdir = "2.5.0"
similar = "2.7.0"
serde_json = "1.0.139"
clap = { version = "4.0", features = ["derive"] }